dist: trusty

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

sudo: required

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/601eba4ae3738ceb2406
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# Install scipy without need to compile, taken from Theano
# Setup anaconda
before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda config --add channels conda-forge

# Install packages
install:
  # Use openblas to fix a theano error (hacky); see http://stackoverflow.com/questions/11987325/theano-fails-due-to-numpy-fortran-mixup-under-ubuntu
  - conda create --name conda-env-python$TRAVIS_PYTHON_VERSION --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose libgfortran six wheel
  - source activate conda-env-python$TRAVIS_PYTHON_VERSION
  - pip install pep8
  - pip install coveralls
  - pip install autograd
  - pip install theano
  - pip install tensorflow
  - python setup.py install

script:
  - nosetests ./tests --nologcapture --verbosity=2 --with-coverage --cover-package=pymanopt
  - pep8 examples pymanopt tests setup.py

after_success:
  - coveralls
